### ISSUE TITLE
Module repository out of date?

### ISSUE THREAD

**Issue by pittjl** [ThreatResponse/margaritashotgun#21]
I'm seeing nothing past June 23 in the standard repository. Did they move to a new location?

**Comment by andrewkrug** [comment]
Thanks for the bug.  It looks like you've got the right repository.  I'm seeing last update times of 6/23 as well.  Investigating this now.

**Comment by andrewkrug** [comment]
@pittjl I think I've sorted out the issue that caused modules not to sync to the s3 bucket.  Please give this a try again and let me know if you run into any problems.
