### ISSUE TITLE
Add timestamp to filename

### ISSUE THREAD

**Issue by KevinHock** [ThreatResponse/margaritashotgun#5]
To prevent accidental overwrites via PutObject you can (a) add a flag to prepend the filename with the timestamp or always do it even when the filename is specified and (b) when there is no filename specified prepend the timestamp with the remote_addr https://github.com/ThreatResponse/margaritashotgun/blob/master/margaritashotgun/remote_host.py#L55

In my opinion GMT time would be best so it wouldn't be effected by local time. I can implement b if I have your blessing for GMT time via

``` python
    from time import gmtime, strftime
    strftime("%Y-%m-%d-%H:%M:%S", gmtime())
```

**Comment by joelferrier** [comment]
I think modifying the default filename (b) is best for now.
I agree UTC/GMT is the way to go, I suggest one minor edit to the format string to match timestamps used in the log file.
https://github.com/ThreatResponse/margaritashotgun/blob/master/margaritashotgun/logger.py#L50

``` python
from time import gmtime, strftime
    strftime("%Y-%m-%dT%H:%M:%S", gmtime())
```

**Comment by KevinHock** [comment]
Done 👍  https://github.com/ThreatResponse/margaritashotgun/pull/6
